version: '3'

services:
  # should starts before api
  api_db:
    container_name: docker-api-db
    image: mongo:latest
    volumes:
      - mongodb_api:/data/db

  api:
    build: ./api
    container_name: docker-api
    command: npm run start
    restart: unless-stopped
    ports:
      # left number - our machine port,
      # right number - our docker container port
      - "3001:3001"
    environment:
      # variables should be provided without any spaces!!!
      # env values that can be ported to js files and be accessible via 'process.env .... '
      - PORT=3001
      - HOST=http://test-docker.com
      # api_db ... host of our aservice, should have same name that has our service for db
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      # express what should this service wait before starts, first will be inited api_db
      - api_db
    volumes:
      - ./api/src:/usr/src/app/src

  auth_db:
    image: mongo:latest
    container_name: docker-auth-db
    volumes:
      - mongodb_auth:/data/db

  auth:
    build: ./auth
    container_name: docker-auth
    command: npm run start
    restart: unless-stopped
    ports: 
      - "3002:3002"
    environment:
      - PORT=3002
      - HOST=http://test-docker.com
      - MONGO_URL=mongodb://auth_db:27017/auth
    depends_on:
      - auth_db

  frontend:
    build: ./frontend
    container_name: docker-frontend
    command: serve -s build -l 3000
    ports:
      - "3000:3000"
    restart: unless-stopped

  nginx:
    image: nginx:stable-alpine
    container_name: docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend

volumes:
  mongodb_api:
  mongodb_auth:
